"test-manager":
  icon: test
  sort: 5
  project:
    - "summary":
        icon: table_chart
        Routes: /testManager/summary
        sort: 1
        permission:
          - 'test-manager-service.test-cycle.getTestCycle'
    - "manager":
        icon: assignment
        Routes: /testManager/manager
        sort: 2
        permission:
          - 'test-manager-service.test-cycle.getTestCycle'
    - "TestPlan":
        icon: poll
        Routes: /testManager/TestPlan
        sort: 3
        permission:
          - 'test-manager-service.test-cycle.getTestCycle'
    - "TestExecute":
        icon: repeat
        Routes: /testManager/TestExecute
        sort: 3
        permission:
          - 'test-manager-service.test-cycle.getTestCycle'

    - "report":
        icon: description
        Routes: /testManager/report
        sort: 4
        permission:
          - 'test-manager-service.test-cycle.getTestCycle'
    - "status":
        icon: filter_vintage
        Routes: /testManager/status
        sort: 5
        permission:
          - 'test-manager-service.test-cycle.getTestCycle'
