"test-manager": TestManager
'test-manager.summary': summary
'test-manager.manager': manager
'test-manager.TestPlan': TestPlan
'test-manager.TestExecute': TestExecute
'test-manager.report':  report
'test-manager.status':  status
