"test-manager": 测试管理
'test-manager.summary': 测试摘要
'test-manager.manager': 测试用例管理
'test-manager.TestPlan': 测试计划
'test-manager.TestExecute': 测试执行
'test-manager.report':  报表
'test-manager.status':  自定义状态
